"""dango/cli/commands/mcp_models.py

MCP model tools: create, update, validate and remove dbt models through Dango's model service.
"""

from __future__ import annotations

import dataclasses
from typing import Any

from dango.cli.commands.mcp_helpers import _get_project_root, _git_warnings
from dango.cli.commands.mcp_server import mcp


def _result_dict(r: Any) -> dict[str, Any]:
    """ModelChangeResult -> JSON-safe dict (dataclasses.asdict), dropping None parse_output."""
    d = dataclasses.asdict(r)
    if d.get("parse_output") is None:
        d.pop("parse_output", None)
    return d


def _service_error(e: Any) -> dict[str, Any]:
    """Service errors verbatim: agents fix models from these exact messages."""
    return {"error": "; ".join(e.errors), "errors": list(e.errors)}


def _with_git_warning(result: dict[str, Any], project_root: Any) -> dict[str, Any]:
    try:
        warnings = _git_warnings(project_root)
    except Exception:  # noqa: BLE001 - the change already landed; never report it as failed
        warnings = []
    if warnings:
        result["git_warning"] = warnings
    return result


@mcp.tool()
def create_model(
    model_name: str,
    layer: str,
    upstream_refs: list[str] | None = None,
    description: str = "",
    sql: str | None = None,
    columns: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Create a dbt model (intermediate or marts) with real SQL, docs and column tests.

    Args:
        model_name: Name for the model. For `intermediate`, `int_` is added automatically.
            Marts names are free-form (fct_/dim_ is only a suggestion).
        layer: `intermediate` or `marts` only. Staging models are generated by sync; use
            `update_model` to customize one.
        upstream_refs: Optional list of models to ref(). Only used to scaffold SQL when `sql`
            is not given.
        description: Model description, written to schema.yml.
        sql: The model's SQL. Pass real SQL using `{{ ref('...') }}` to staging, intermediate
            or marts models (never `source()` outside staging). Omit for a scaffold.
        columns: Optional list of `{"name", "description"?, "data_tests"?}` entries for schema.yml.

    Runs `dbt parse` before and after writing and rolls back on a failure it caused. Validation
    errors come back as `errors` (a list) and nothing is written. Then run
    `run_transform(select=<model_name>)` to build it.

    Returns dict with: status, model_name, layer, path, files_changed, refs, sources, warnings,
    parse_ok, git_warning (if any), or error/errors.
    """
    project_root = _get_project_root()
    if sql is not None and not sql.strip():
        return {"error": "SQL is empty", "errors": ["SQL is empty"]}
    try:
        from dango.transformation.model_service import ModelServiceError
        from dango.transformation.model_service import create_model as _create

        try:
            r = _create(
                project_root,
                model_name,
                layer,
                sql=sql,
                upstream=upstream_refs,
                description=description,
                columns=columns,
            )
        except ModelServiceError as e:
            return _service_error(e)
        return _with_git_warning(_result_dict(r), project_root)
    except Exception as e:  # noqa: BLE001
        return {"error": str(e)}


@mcp.tool()
def update_model(
    model_name: str,
    sql: str | None = None,
    description: str | None = None,
    columns: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Update an existing model's SQL and/or schema.yml docs.

    Works for staging models too: changing a staging model's SQL marks it customized so sync
    stops regenerating it. A supplied `data_tests` list REPLACES that column's existing list;
    other schema.yml content is kept. Existing models that call `source()` outside staging are
    rejected with a lineage error until fixed. Runs `dbt parse` before and after and rolls back
    on a failure it caused.

    Args:
        model_name: Existing model name.
        sql: New SQL (omit to leave unchanged).
        description: New description (omit to leave unchanged).
        columns: `{"name", "description"?, "data_tests"?}` entries, merged by column name.

    Returns dict with: status, model_name, layer, files_changed, refs, sources, warnings,
    parse_ok, git_warning (if any), or error/errors.
    """
    project_root = _get_project_root()
    try:
        from dango.transformation.model_service import ModelServiceError
        from dango.transformation.model_service import update_model as _update

        try:
            r = _update(project_root, model_name, sql=sql, description=description, columns=columns)
        except ModelServiceError as e:
            return _service_error(e)
        return _with_git_warning(_result_dict(r), project_root)
    except Exception as e:  # noqa: BLE001
        return {"error": str(e)}


@mcp.tool()
def validate_model(model_name: str, layer: str, sql: str) -> dict[str, Any]:
    """Check model SQL without writing anything.

    Static checks only (refs exist, lineage, cycles, naming, name not already taken for
    intermediate/marts); `dbt parse` runs on create_model / update_model. For an existing
    model, pass its layer and expect the name-taken error; use update_model to apply changes.

    Args:
        model_name: Model name (normalized for the layer, e.g. `int_` prefix).
        layer: `staging`, `intermediate` or `marts`.
        sql: The SQL to check.

    Returns dict with: valid, model_name, warnings, refs, sources; or valid=False with
    error/errors.
    """
    project_root = _get_project_root()
    try:
        from dango.transformation.model_service import (
            ModelServiceError,
            extract_refs,
            find_model,
            normalize_model_name,
            render_model_sql,
            validate_model_sql,
        )

        try:
            name = normalize_model_name(model_name, layer)
            if not sql.strip():
                raise ModelServiceError(["SQL is empty"])
            existing = find_model(project_root, name) if layer != "staging" else None
            if existing:
                raise ModelServiceError(
                    [
                        f"Model '{name}' already exists ({existing[0].relative_to(project_root)}); "
                        "use update_model to change it"
                    ]
                )
            rendered = render_model_sql(name, layer, sql=sql)
            warnings = validate_model_sql(project_root, name, layer, rendered)
        except ModelServiceError as e:
            return {"valid": False, **_service_error(e)}
        refs, sources = extract_refs(rendered)
        return {
            "valid": True,
            "model_name": name,
            "warnings": warnings,
            "refs": refs,
            "sources": sources,
        }
    except Exception as e:  # noqa: BLE001
        return {"valid": False, "error": str(e)}


@mcp.tool()
def remove_model(
    model_name: str,
    drop_table: bool = True,
    dry_run: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    """Remove a custom (intermediate/marts) model: SQL file, schema.yml entry, monitors, table.

    Call with `dry_run=True` first to see downstream models, monitors and the table. `force=True`
    is required when downstream models exist. A held lock (sync or dbt running) returns an error
    after 30 s. Staging models cannot be removed (remove the source instead).

    Args:
        model_name: Model to remove.
        drop_table: Also drop the warehouse table (default True).
        dry_run: Report what would be removed without changing anything.
        force: Remove even when other models depend on it.

    Returns dict with: status (removed | dry_run), path, files_changed, downstream, monitors_removed, table_existed,
    dropped_table, metabase (refreshed | not_running, after a drop), git_warning (if any),
    or error/errors.
    """
    project_root = _get_project_root()
    try:
        from dango.transformation.model_service import ModelServiceError
        from dango.transformation.model_service import remove_model as _remove

        try:
            r = _remove(
                project_root,
                model_name,
                drop_table=drop_table,
                dry_run=dry_run,
                force=force,
                lock_source="mcp",
                lock_timeout=30,
            )
        except ModelServiceError as e:
            return _service_error(e)
        out = _result_dict(r)
        if r.dropped_table:
            out["metabase"] = _refresh_metabase(project_root)
        if not dry_run:
            _with_git_warning(out, project_root)
        return out
    except Exception as e:  # noqa: BLE001
        return {"error": str(e)}


def _refresh_metabase(project_root: Any) -> str:
    """Best-effort Metabase refresh after a table drop (same as `dango model remove`)."""
    try:
        from dango.visualization.metabase import (
            refresh_metabase_connection,
            sync_metabase_schema,
        )

        ok, _err, session_id = refresh_metabase_connection(project_root)
        if ok and sync_metabase_schema(project_root, existing_session_id=session_id):
            return "refreshed"
    except Exception:  # noqa: BLE001
        pass
    return "not_running"
