"""dango/transformation/model_service.py

Non-interactive dbt model create/update/remove with Dango's naming, lineage and docs rules.
"""

import difflib
import re
import subprocess
from pathlib import Path
from typing import Any

from dango.transformation.model_common import (
    CUSTOM_MODEL_LAYERS,
    MODEL_LAYERS,
    ModelChangeResult,
    ModelServiceError,
    find_model,
    iter_model_files,
    list_models,
    normalize_model_name,
    rel_path,
    stems,
)
from dango.transformation.model_docs import (
    locate_model_docs,
    remove_model_docs,
    resolve_docs_path,
    upsert_model_docs,
)
from dango.transformation.model_sql import extract_refs, render_model_sql, validate_model_sql

__all__ = [
    "CUSTOM_MODEL_LAYERS",
    "MODEL_LAYERS",
    "ModelChangeResult",
    "ModelServiceError",
    "create_model",
    "extract_refs",
    "find_model",
    "list_models",
    "locate_model_docs",
    "normalize_model_name",
    "parse_project",
    "remove_model",
    "remove_model_docs",
    "render_model_sql",
    "update_model",
    "upsert_model_docs",
    "validate_model_sql",
]

_VALID_MODEL_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")  # same rule as commands/model.py
_AUTOGEN_MARKER = "-- Auto-generated by Dango"


def parse_project(project_root: Path) -> tuple[bool, str]:
    """Run ``dbt parse`` (no DuckDB writes, so no DbtLock); returns (ok, combined output)."""
    from dango.transformation import _dbt_telemetry_env, _get_dbt_executable

    dbt_dir = project_root / "dbt"
    try:
        result = subprocess.run(
            [
                _get_dbt_executable(),
                "parse",
                "--project-dir",
                str(dbt_dir),
                "--profiles-dir",
                str(dbt_dir),
            ],
            cwd=str(project_root),
            capture_output=True,
            stdin=subprocess.DEVNULL,  # never inherit the MCP server's JSON-RPC stdin
            text=True,
            timeout=30,
            env=_dbt_telemetry_env(),
        )
        return result.returncode == 0, (result.stdout or "") + (result.stderr or "")
    except subprocess.TimeoutExpired:
        return False, "dbt parse timed out after 30 seconds"
    except Exception as e:  # noqa: BLE001
        return False, f"dbt parse could not run: {e}"


class _Snapshot:
    """Remembers prior bytes of files (None = absent) so a failed change can be undone."""

    def __init__(self) -> None:
        self._prior: dict[Path, bytes | None] = {}

    def take(self, path: Path) -> None:
        """Record path's current bytes (once)."""
        if path not in self._prior:
            self._prior[path] = path.read_bytes() if path.exists() else None

    def restore(self) -> None:
        """Put every recorded file back (delete files that did not exist)."""
        for path, content in self._prior.items():
            if content is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(content)


def _check_upstream_exists(project_root: Path, upstream: list[str]) -> list[str]:
    known = (
        set(list_models(project_root))
        | stems(project_root, "seeds", "*.csv")
        | stems(project_root, "snapshots", "*.sql")
    )
    return [f"upstream model '{u}' does not exist" for u in upstream if u not in known]


def _apply(
    project_root: Path,
    result: ModelChangeResult,
    sql_path: Path,
    content: str | None,
    layer: str,
    name: str,
    description: str | None,
    columns: list[dict[str, Any]] | None,
    parse: bool,
) -> None:
    """Write sql + docs with a parse gate: roll back if dbt parse newly fails."""
    baseline_ok: bool | None = None
    if parse:
        baseline_ok, _ = parse_project(project_root)

    snap = _Snapshot()
    snap.take(sql_path)
    docs_wanted = description is not None or bool(columns)
    if docs_wanted:
        snap.take(resolve_docs_path(project_root, layer, name))
    try:
        if content is not None:
            sql_path.parent.mkdir(parents=True, exist_ok=True)
            sql_path.write_text(content)
            result.files_changed.append(rel_path(project_root, sql_path))
        if docs_wanted:
            docs_rel = upsert_model_docs(
                project_root, layer, name, description=description, columns=columns
            )
            if docs_rel:
                result.files_changed.append(docs_rel)
    except BaseException:
        snap.restore()
        raise

    if not parse:
        return
    if baseline_ok is False:
        result.parse_ok = False
        result.warnings.append("project already fails dbt parse before this change")
        return
    ok, out = parse_project(project_root)
    result.parse_ok = ok
    if not ok:
        snap.restore()
        raise ModelServiceError(
            [f"dbt parse failed after this change; it was rolled back. Output tail: {out[-4000:]}"]
        )


# ---------------------------------------------------------------------------
# create / update / remove
# ---------------------------------------------------------------------------


def create_model(
    project_root: Path,
    name: str,
    layer: str,
    *,
    sql: str | None = None,
    upstream: list[str] | None = None,
    description: str = "",
    columns: list[dict[str, Any]] | None = None,
    materialization: str = "table",
    write_docs: bool = True,
    parse: bool = True,
) -> ModelChangeResult:
    """Create an intermediate or marts model; validates everything before writing."""
    if layer not in CUSTOM_MODEL_LAYERS:
        raise ModelServiceError(
            ["staging models are generated by sync; use update_model to customize an existing one"]
        )
    model_name = normalize_model_name(name, layer)
    existing = find_model(project_root, model_name)
    if existing:
        path, existing_layer = existing
        where = "already exists" if existing_layer == layer else "already exists in another layer"
        raise ModelServiceError(
            [
                f"Model '{model_name}' {where} ({rel_path(project_root, path)}); "
                "dbt requires unique model names across all layers"
            ]
        )
    upstream = upstream or []
    missing = _check_upstream_exists(project_root, upstream)
    if missing:
        raise ModelServiceError(missing)
    if columns:
        for col in columns:
            if not isinstance(col, dict) or not col.get("name"):
                raise ModelServiceError(["every column entry must be a mapping with a 'name'"])

    rendered = render_model_sql(
        model_name,
        layer,
        sql=sql,
        upstream=upstream,
        description=description,
        materialization=materialization,
    )
    warnings = validate_model_sql(project_root, model_name, layer, rendered)
    refs, sources = extract_refs(rendered)

    sql_path = project_root / "dbt" / "models" / layer / f"{model_name}.sql"
    result = ModelChangeResult(
        model_name=model_name,
        layer=layer,
        status="created",
        path=rel_path(project_root, sql_path),
        warnings=warnings,
        refs=refs,
        sources=sources,
    )
    docs = write_docs and bool(description or columns)
    _apply(
        project_root,
        result,
        sql_path,
        rendered,
        layer,
        model_name,
        description or None if docs else None,
        columns if docs else None,
        parse,
    )
    return result


def update_model(
    project_root: Path,
    name: str,
    *,
    sql: str | None = None,
    description: str | None = None,
    columns: list[dict[str, Any]] | None = None,
    parse: bool = True,
) -> ModelChangeResult:
    """Update an existing model's SQL and/or docs (staging included)."""
    model_name = name.strip().lower().removesuffix(".sql")
    found = find_model(project_root, model_name)
    if found is None:
        msg = f"Model '{model_name}' not found"
        close = difflib.get_close_matches(model_name, sorted(list_models(project_root)), n=1)
        if close:
            msg += f" (did you mean '{close[0]}'?)"
        raise ModelServiceError([msg])
    sql_path, layer = found
    if sql is None and description is None and not columns:
        raise ModelServiceError(["nothing to update: pass sql, description or columns"])

    warnings: list[str] = []
    rendered: str | None = None
    refs: list[str] = []
    sources: list[str] = []
    if sql is not None:
        rendered = render_model_sql(model_name, layer, sql=sql)
        if layer == "staging":
            current_auto = _AUTOGEN_MARKER in sql_path.read_text()[:500]
            kept = [ln for ln in rendered.splitlines() if _AUTOGEN_MARKER not in ln]
            if len(kept) != len(rendered.splitlines()) or current_auto:
                warnings.append(
                    "Removed the auto-generated marker so sync treats this staging model as "
                    "customized and will not overwrite it"
                )
            rendered = "\n".join(kept).rstrip() + "\n"
        warnings += validate_model_sql(project_root, model_name, layer, rendered)
        refs, sources = extract_refs(rendered)
    if columns:
        for col in columns:
            if not isinstance(col, dict) or not col.get("name"):
                raise ModelServiceError(["every column entry must be a mapping with a 'name'"])

    result = ModelChangeResult(
        model_name=model_name,
        layer=layer,
        status="updated",
        path=rel_path(project_root, sql_path),
        warnings=warnings,
        refs=refs,
        sources=sources,
    )
    _apply(
        project_root,
        result,
        sql_path,
        rendered,
        layer,
        model_name,
        description,
        columns,
        parse,
    )
    return result


def _warehouse_has_table(project_root: Path, layer: str, name: str) -> bool | None:
    """True/False, or None when the warehouse exists but could not be read (e.g. locked)."""
    import duckdb

    duckdb_path = project_root / "data" / "warehouse.duckdb"
    if not duckdb_path.exists():
        return False
    try:
        conn = duckdb.connect(str(duckdb_path), config={"access_mode": "read_only"})
        try:
            row = conn.execute(
                "SELECT COUNT(*) FROM information_schema.tables "
                "WHERE table_schema = ? AND table_name = ?",
                [layer, name],
            ).fetchone()
            return bool(row and row[0] > 0)
        finally:
            conn.close()
    except Exception:  # noqa: BLE001
        return None


def remove_model(
    project_root: Path,
    name: str,
    *,
    drop_table: bool = True,
    dry_run: bool = False,
    force: bool = False,
    lock_source: str = "cli",
    lock_timeout: float = 300,
) -> ModelChangeResult:
    """Remove a custom model: sql, docs entry, monitors and (under DbtLock) its table."""
    model_name = name.strip().lower().removesuffix(".sql")
    if not _VALID_MODEL_NAME_RE.match(model_name):
        raise ModelServiceError([f"Invalid model name '{model_name}'"])
    found = find_model(project_root, model_name)
    if found is None:
        raise ModelServiceError([f"Model '{model_name}' not found"])
    sql_path, layer = found
    if layer not in CUSTOM_MODEL_LAYERS:
        raise ModelServiceError(
            [f"'{model_name}' is a staging model generated by sync; remove the source instead"]
        )

    downstream: list[str] = []
    for path, other_layer in iter_model_files(project_root):
        if path == sql_path:
            continue
        try:
            other_refs, _ = extract_refs(path.read_text())
        except OSError:
            continue
        if model_name in other_refs:
            downstream.append(f"{other_layer}.{path.stem}")

    table_state = _warehouse_has_table(project_root, layer, model_name)
    table_existed = table_state is True
    table_unknown = table_state is None

    monitors: list[str] = []
    try:
        from dango.analysis.config import load_monitors_config

        monitors = [
            m.name
            for m in load_monitors_config(project_root).monitors
            if m.source_table.endswith(f".{model_name}")
        ]
    except Exception:  # noqa: BLE001
        pass

    docs_path = locate_model_docs(project_root, model_name)
    files = [rel_path(project_root, sql_path)]
    if docs_path:
        files.append(rel_path(project_root, docs_path))
    if monitors:
        files.append(".dango/monitors.yml")
    result = ModelChangeResult(
        model_name=model_name,
        layer=layer,
        status="dry_run" if dry_run else "removed",
        path=rel_path(project_root, sql_path),
        files_changed=files,
        downstream=downstream,
        table_existed=table_existed,
        monitors_removed=monitors,
    )
    if table_unknown:
        result.warnings.append(
            "Could not read the warehouse (it may be locked by a running sync or server); "
            "the model's table may still exist"
        )
    if dry_run:
        return result
    if downstream and not force:
        raise ModelServiceError([f"Other models depend on '{model_name}': {', '.join(downstream)}"])

    lock = None
    if drop_table and (table_existed or table_unknown):
        from dango.utils import DbtLock, DbtLockError

        lock = DbtLock(
            project_root=project_root, source=lock_source, operation=f"remove model {model_name}"
        )
        try:
            lock.acquire(timeout=lock_timeout)
        except DbtLockError as e:
            raise ModelServiceError(
                [f"Could not acquire the dbt lock; nothing removed: {e}"]
            ) from e
    try:
        sql_path.unlink()
        remove_model_docs(project_root, layer, model_name)
        if monitors:
            try:
                from dango.analysis.config import load_monitors_config, save_monitors_config
                from dango.analysis.models import MonitorsConfig

                cfg = load_monitors_config(project_root)
                kept = [m for m in cfg.monitors if m.name not in monitors]
                # MonitorsConfig is frozen — create a new instance
                save_monitors_config(project_root, MonitorsConfig(monitors=kept))
            except Exception:  # noqa: BLE001
                result.warnings.append("Could not update monitors.yml")
        if lock is not None:
            import duckdb

            try:
                # layer is from CUSTOM_MODEL_LAYERS and model_name matches
                # _VALID_MODEL_NAME_RE, so interpolation is safe
                conn = duckdb.connect(str(project_root / "data" / "warehouse.duckdb"))
                try:
                    conn.execute(f'DROP TABLE IF EXISTS "{layer}"."{model_name}"')
                finally:
                    conn.close()
                result.dropped_table = True
            except Exception as e:  # noqa: BLE001
                result.warnings.append(f"Failed to drop table {layer}.{model_name}: {e}")
    finally:
        if lock is not None and lock._acquired:
            lock.release()
    return result
