-- Auto-generated by Dango
-- Joins geographic_stats with geo_targets seed for country names
-- To customize: edit this file (it will not be regenerated)

{{ config(
    materialized='table',
    schema='staging'
) }}

SELECT
    gs.*,
    gt.name as geo_name,
    gt.canonical_name as geo_canonical_name
FROM {{ source('__SOURCE_NAME__', 'geographic_stats') }} gs
LEFT JOIN {{ ref('geo_targets') }} gt
    ON gs.geographic_view_country_criterion_id = gt.criteria_id
