"""tests/unit/test_snapshot_cmd.py

Tests for dango.cli.commands.snapshot — dbt snapshot commands.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest


@pytest.mark.unit
class TestSnapshotTemplate:
    """Test that the Jinja2 template renders valid dbt snapshot SQL."""

    def _render(self, **kwargs):
        import jinja2

        templates_dir = Path(__file__).parent.parent.parent / "dango" / "templates" / "dbt"
        env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(templates_dir)),
            keep_trailing_newline=True,
        )
        template = env.get_template("snapshot.sql.j2")
        return template.render(**kwargs)

    def test_timestamp_strategy(self):
        rendered = self._render(
            generated_at="2026-05-06 12:00",
            snapshot_name="snap_shopify_orders",
            source_name="shopify",
            table_name="orders",
            strategy="timestamp",
            unique_key="id",
            updated_at="updated_at",
        )

        assert "{% snapshot snap_shopify_orders %}" in rendered
        assert "unique_key='id'" in rendered
        assert "strategy='timestamp'" in rendered
        assert "updated_at='updated_at'" in rendered
        assert "check_cols" not in rendered
        assert "{{ source('shopify', 'orders') }}" in rendered
        assert "{% endsnapshot %}" in rendered

    def test_check_strategy(self):
        rendered = self._render(
            generated_at="2026-05-06 12:00",
            snapshot_name="snap_stripe_customers",
            source_name="stripe",
            table_name="customers",
            strategy="check",
            unique_key="uuid",
            updated_at="",
        )

        assert "{% snapshot snap_stripe_customers %}" in rendered
        assert "unique_key='uuid'" in rendered
        assert "strategy='check'" in rendered
        assert "check_cols='all'" in rendered
        assert "updated_at" not in rendered.split("check_cols")[1]
        assert "{{ source('stripe', 'customers') }}" in rendered

    def test_header_comment(self):
        rendered = self._render(
            generated_at="2026-05-06 12:00",
            snapshot_name="snap_test_users",
            source_name="test",
            table_name="users",
            strategy="check",
            unique_key="id",
            updated_at="",
        )

        assert "Auto-generated by Dango" in rendered
        assert "Snapshot: snap_test_users" in rendered
        assert "Source: test.users" in rendered
        assert "Strategy: check" in rendered
        assert "SCD Type 2" in rendered


@pytest.mark.unit
class TestSnapshotList:
    """Test snapshot list command parsing."""

    def test_no_snapshots_dir(self, tmp_path):
        """List with no snapshots directory shows empty message."""
        from click.testing import CliRunner

        from dango.cli.commands.snapshot import snapshot

        runner = CliRunner()
        with patch("dango.cli.utils.find_project_root", return_value=tmp_path):
            result = runner.invoke(snapshot, ["list"], obj={"project_root": tmp_path})

        assert "No dbt snapshots configured" in result.output

    def test_parses_existing_snapshots(self, tmp_path):
        """List with existing snapshot files parses and displays them."""
        from click.testing import CliRunner

        from dango.cli.commands.snapshot import snapshot

        snapshots_dir = tmp_path / "dbt" / "snapshots"
        snapshots_dir.mkdir(parents=True)

        snapshot_sql = """\
{% snapshot snap_shopify_orders %}

  {{
    config(
      target_schema='snapshots',
      unique_key='id',
      strategy='timestamp',
      updated_at='updated_at'
    )
  }}

  SELECT * FROM {{ source('shopify', 'orders') }}

{% endsnapshot %}
"""
        (snapshots_dir / "snap_shopify_orders.sql").write_text(snapshot_sql)

        runner = CliRunner()
        with patch("dango.cli.utils.find_project_root", return_value=tmp_path):
            result = runner.invoke(snapshot, ["list"], obj={"project_root": tmp_path})

        assert result.exit_code == 0
        # Rich may truncate long names — check for partial matches
        assert "snap_shopify" in result.output
        assert "shopify.orders" in result.output
        assert "timestamp" in result.output


@pytest.mark.unit
class TestSnapshotRun:
    """Test snapshot run command."""

    def test_invokes_dbt_snapshot(self, tmp_path):
        """Run command calls run_dbt_snapshots and acquires DbtLock."""
        from click.testing import CliRunner

        from dango.cli.commands.snapshot import snapshot

        # Create dbt/snapshots/ directory with a file
        snapshots_dir = tmp_path / "dbt" / "snapshots"
        snapshots_dir.mkdir(parents=True)
        (snapshots_dir / "snap_test.sql").write_text("-- snapshot")

        # Also need .dango/state/ for the lock
        state_dir = tmp_path / ".dango" / "state"
        state_dir.mkdir(parents=True)

        runner = CliRunner()
        with (
            patch("dango.cli.utils.find_project_root", return_value=tmp_path),
            patch(
                "dango.transformation.run_dbt_snapshots",
                return_value=(True, "Success"),
            ) as mock_run,
        ):
            result = runner.invoke(snapshot, ["run"], obj={"project_root": tmp_path})

        assert result.exit_code == 0
        assert "completed successfully" in result.output
        mock_run.assert_called_once_with(tmp_path, select=None)

    def test_no_dbt_directory(self, tmp_path):
        """Run command errors when dbt directory is missing."""
        from click.testing import CliRunner

        from dango.cli.commands.snapshot import snapshot

        runner = CliRunner()
        with patch("dango.cli.utils.find_project_root", return_value=tmp_path):
            result = runner.invoke(snapshot, ["run"], obj={"project_root": tmp_path})

        assert result.exit_code != 0
        assert "dbt directory not found" in result.output


@pytest.mark.unit
class TestRunDbtSnapshots:
    """Test the run_dbt_snapshots() function in transformation/__init__.py."""

    def test_builds_correct_command(self, tmp_path):
        """run_dbt_snapshots builds correct dbt command."""
        dbt_dir = tmp_path / "dbt"
        dbt_dir.mkdir()

        with patch("dango.transformation.subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=0, stdout="ok", stderr="")

            from dango.transformation import run_dbt_snapshots

            success, output = run_dbt_snapshots(tmp_path)

        assert success is True
        cmd = mock_run.call_args[0][0]
        assert "snapshot" in cmd
        assert "--project-dir" in cmd
        assert "--profiles-dir" in cmd

    def test_select_option(self, tmp_path):
        """run_dbt_snapshots passes --select when specified."""
        dbt_dir = tmp_path / "dbt"
        dbt_dir.mkdir()

        with patch("dango.transformation.subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=0, stdout="ok", stderr="")

            from dango.transformation import run_dbt_snapshots

            success, output = run_dbt_snapshots(tmp_path, select="snap_test")

        cmd = mock_run.call_args[0][0]
        assert "--select" in cmd
        assert "snap_test" in cmd

    def test_failure_returns_structured_error(self, tmp_path):
        """run_dbt_snapshots returns structured error on failure."""
        dbt_dir = tmp_path / "dbt"
        dbt_dir.mkdir()

        with patch("dango.transformation.subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(
                returncode=1, stdout="Compilation Error in snapshot", stderr=""
            )

            from dango.transformation import run_dbt_snapshots

            success, output = run_dbt_snapshots(tmp_path)

        assert success is False
        assert "dbt snapshot failed" in output

    def test_timeout_returns_error(self, tmp_path):
        """run_dbt_snapshots handles timeout."""
        import subprocess

        dbt_dir = tmp_path / "dbt"
        dbt_dir.mkdir()

        with patch("dango.transformation.subprocess.run") as mock_run:
            mock_run.side_effect = subprocess.TimeoutExpired(cmd="dbt", timeout=300)

            from dango.transformation import run_dbt_snapshots

            success, output = run_dbt_snapshots(tmp_path)

        assert success is False
        assert "timed out" in output
