"""tests/unit/test_mcp_models.py

Tests for the MCP model tools (dango/cli/commands/mcp_models.py) over a real project in tmp_path.
The M5 model service holds the rules; these tests cover the thin MCP layer on top of it.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any

import pytest
import yaml

from dango.cli.commands import mcp_models

STG = "stg_x__orders"
STG_SQL = "-- Auto-generated by Dango\nselect 1 as order_id, 'eu' as region, 5 as amount\n"
MARTS_SQL = "select region, sum(amount) as total from {{ ref('stg_x__orders') }} group by 1\n"


@pytest.fixture
def project(tmp_path: Path, sample_config, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Real project with one staging model; dbt parse is patched out."""
    from dango.config.helpers import save_config

    save_config(sample_config, tmp_path)
    stg = tmp_path / "dbt" / "models" / "staging"
    stg.mkdir(parents=True)
    (stg / f"{STG}.sql").write_text(STG_SQL)
    monkeypatch.setattr(mcp_models, "_get_project_root", lambda: tmp_path)
    monkeypatch.setattr(mcp_models, "_git_warnings", lambda project_root: [])
    monkeypatch.setattr("dango.transformation.model_service.parse_project", lambda root: (True, ""))
    return tmp_path


def _tree(root: Path) -> dict[str, bytes]:
    return {str(p.relative_to(root)): p.read_bytes() for p in root.rglob("*") if p.is_file()}


def _schema(root: Path, layer: str) -> dict[str, Any]:
    return yaml.safe_load((root / "dbt" / "models" / layer / "schema.yml").read_text())


@pytest.mark.unit
class TestCreateModel:
    def test_create_model_with_sql_and_docs(self, project: Path) -> None:
        result = mcp_models.create_model(
            "revenue_by_region",
            "marts",
            description="Revenue per region",
            sql=MARTS_SQL,
            columns=[{"name": "region", "data_tests": ["not_null"]}],
        )
        assert result["status"] == "created"
        assert result["refs"] == [STG]
        assert (project / "dbt/models/marts/revenue_by_region.sql").exists()
        entry = _schema(project, "marts")["models"][0]
        assert entry["name"] == "revenue_by_region"
        assert entry["description"] == "Revenue per region"
        assert entry["columns"][0]["data_tests"] == ["not_null"]

    def test_create_model_errors_are_verbatim_list(self, project: Path) -> None:
        from dango.transformation.model_service import ModelServiceError, validate_model_sql

        sql = "select * from {{ ref('nope') }} join {{ source('x', 'orders') }} using (id)"
        with pytest.raises(ModelServiceError) as exc:
            validate_model_sql(project, "m", "marts", sql)
        before = _tree(project)
        result = mcp_models.create_model("m", "marts", sql=sql)
        assert result["errors"] == exc.value.errors
        assert len(result["errors"]) == 2
        assert result["error"] == "; ".join(exc.value.errors)
        assert _tree(project) == before

    def test_create_model_rejects_staging_layer(self, project: Path) -> None:
        before = _tree(project)
        result = mcp_models.create_model("stg_x__new", "staging", sql="select 1")
        assert "generated by sync" in result["error"]
        assert _tree(project) == before

    def test_create_model_marts_name_free_form_warning(self, project: Path) -> None:
        result = mcp_models.create_model("revenue_by_week", "marts", sql=MARTS_SQL)
        assert result["status"] == "created"
        assert any("fct_" in w and "dim_" in w for w in result["warnings"])

    def test_create_model_legacy_signature(self, project: Path) -> None:
        result = mcp_models.create_model("int_orders", "intermediate", [STG])
        assert result["status"] == "created"
        assert result["model_name"] == "int_orders"
        assert result["refs"] == [STG]

    def test_create_model_unexpected_exception_returns_error(
        self, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def boom(*a: Any, **k: Any) -> None:
            raise RuntimeError("kaput")

        monkeypatch.setattr("dango.transformation.model_service.create_model", boom)
        assert mcp_models.create_model("m", "marts", sql="select 1") == {"error": "kaput"}


@pytest.mark.unit
class TestUpdateModel:
    def test_update_model_docs_only_preserves_sql_bytes(self, project: Path) -> None:
        mcp_models.create_model("revenue_by_region", "marts", sql=MARTS_SQL)
        path = project / "dbt/models/marts/revenue_by_region.sql"
        before = path.read_bytes()
        result = mcp_models.update_model(
            "revenue_by_region",
            description="New desc",
            columns=[{"name": "total", "description": "Sum"}],
        )
        assert result["status"] == "updated"
        assert path.read_bytes() == before
        entry = _schema(project, "marts")["models"][0]
        assert entry["description"] == "New desc"
        assert entry["columns"][0]["name"] == "total"

    def test_update_staging_marks_customized(self, project: Path) -> None:
        result = mcp_models.update_model(STG, sql="select 2 as order_id")
        assert result["status"] == "updated"
        text = (project / f"dbt/models/staging/{STG}.sql").read_text()
        assert "Auto-generated by Dango" not in text
        assert any("customized" in w for w in result["warnings"])


@pytest.mark.unit
class TestValidateModel:
    def test_validate_model_no_writes(self, project: Path) -> None:
        mcp_models.create_model("a_mart", "marts", sql=MARTS_SQL)
        before = _tree(project)
        ok = mcp_models.validate_model(
            "int_ok", "intermediate", "select * from {{ ref('a_mart') }}"
        )
        assert ok["valid"] is False  # intermediate must not ref marts
        good = mcp_models.validate_model(
            "int_ok", "intermediate", f"select * from {{{{ ref('{STG}') }}}}"
        )
        assert good["valid"] is True
        assert good["model_name"] == "int_ok"
        assert good["refs"] == [STG]
        # a_mart refs stg; making stg ref a_mart is a cycle
        cyc = mcp_models.validate_model(STG, "staging", "select * from {{ ref('a_mart') }}")
        assert cyc["valid"] is False
        cyc2 = mcp_models.validate_model("b_mart", "marts", "select * from {{ ref('b_mart') }}")
        assert cyc2["valid"] is False and cyc2["errors"]
        assert _tree(project) == before


@pytest.mark.unit
class TestRemoveModel:
    def test_remove_model_dry_run_then_force(self, project: Path) -> None:
        mcp_models.create_model("revenue_by_region", "marts", sql=MARTS_SQL)
        mcp_models.create_model(
            "top_region", "marts", sql="select * from {{ ref('revenue_by_region') }}"
        )
        blocked = mcp_models.remove_model("revenue_by_region")
        assert "top_region" in blocked["error"]
        assert (project / "dbt/models/marts/revenue_by_region.sql").exists()
        dry = mcp_models.remove_model("revenue_by_region", dry_run=True)
        assert dry["status"] == "dry_run"
        assert dry["downstream"] == ["marts.top_region"]
        assert (project / "dbt/models/marts/revenue_by_region.sql").exists()
        done = mcp_models.remove_model("revenue_by_region", force=True)
        assert done["status"] == "removed"
        assert not (project / "dbt/models/marts/revenue_by_region.sql").exists()

    def test_remove_model_uses_mcp_lock_settings(
        self, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from dango.transformation.model_common import ModelChangeResult

        seen: dict[str, Any] = {}

        def fake(root: Path, name: str, **kw: Any) -> ModelChangeResult:
            seen.update(kw)
            return ModelChangeResult(model_name=name, layer="marts", status="removed", path=None)

        monkeypatch.setattr("dango.transformation.model_service.remove_model", fake)
        mcp_models.remove_model("m")
        assert seen["lock_source"] == "mcp"
        assert seen["lock_timeout"] == 30

    @pytest.mark.parametrize("dropped,expect_calls", [(True, 1), (False, 0)])
    def test_remove_model_refreshes_metabase_after_drop(
        self, project: Path, monkeypatch: pytest.MonkeyPatch, dropped: bool, expect_calls: int
    ) -> None:
        from dango.transformation.model_common import ModelChangeResult

        monkeypatch.setattr(
            "dango.transformation.model_service.remove_model",
            lambda root, name, **kw: ModelChangeResult(
                model_name=name, layer="marts", status="removed", path=None, dropped_table=dropped
            ),
        )
        calls: list[str] = []
        monkeypatch.setattr(
            "dango.visualization.metabase.refresh_metabase_connection",
            lambda root: (calls.append("refresh") or True, None, "sid"),
        )
        monkeypatch.setattr(
            "dango.visualization.metabase.sync_metabase_schema",
            lambda root, existing_session_id=None: calls.append("sync") is None,
        )
        result = mcp_models.remove_model("m")
        assert len(calls) == expect_calls * 2
        if dropped:
            assert result["metabase"] == "refreshed"
        else:
            assert "metabase" not in result

    def test_remove_model_metabase_not_running(
        self, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from dango.transformation.model_common import ModelChangeResult

        monkeypatch.setattr(
            "dango.transformation.model_service.remove_model",
            lambda root, name, **kw: ModelChangeResult(
                model_name=name, layer="marts", status="removed", path=None, dropped_table=True
            ),
        )

        def boom(root: Path) -> None:
            raise ConnectionError("down")

        monkeypatch.setattr("dango.visualization.metabase.refresh_metabase_connection", boom)
        assert mcp_models.remove_model("m")["metabase"] == "not_running"


@pytest.mark.unit
class TestGitWarningAndRegistration:
    def test_git_warning_only_on_successful_writes(
        self, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(mcp_models, "_git_warnings", lambda project_root: ["dirty tree"])
        ok = mcp_models.create_model("revenue_by_region", "marts", sql=MARTS_SQL)
        assert ok["git_warning"] == ["dirty tree"]
        assert mcp_models.update_model("revenue_by_region", description="d")["git_warning"] == [
            "dirty tree"
        ]
        assert "git_warning" not in mcp_models.create_model(
            "bad", "marts", sql="select 1 from {{ ref('zzz') }}"
        )
        assert "git_warning" not in mcp_models.validate_model("v", "marts", MARTS_SQL)
        assert "git_warning" not in mcp_models.remove_model("revenue_by_region", dry_run=True)
        assert mcp_models.remove_model("revenue_by_region")["git_warning"] == ["dirty tree"]

    def test_model_tools_registered(self) -> None:
        from dango.cli.commands import mcp_server

        names = {t.name for t in asyncio.run(mcp_server.mcp.list_tools())}
        assert {"create_model", "update_model", "validate_model", "remove_model"} <= names
        assert {"run_sync", "run_transform", "add_source", "query"} <= names
